name: Keploy API Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  keploy-api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Start Next.js server in background
        run: |
          npm run start &
          sleep 10

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        env:
          KEPLOY_API_KEY: ${{ secrets.KEPLOY_API_KEY }}
        run: |
          keploy test-suite \
            --app=82f7424b-e185-444c-af3f-7e485a16a4e6 \
            --base-path http://localhost:3000 \
            --cloud
